language: python
python:
  - "2.7"
  - "3.5"
install:
  - travis_wait 20 pip install -r requirements.txt
  - pip install .
script: 
  - (cd test_scripts/ && for i in *.sh; do ./"$i" ; done)
  - py.test
